### ISSUE TITLE
Mac OS "os.arch" Values

### ISSUE THREAD

**Issue by noboomu** [wilsonzlin/minify-html#10]
On some mac os machines we have tested with JDK > 11, `System.getProperty("os.arch")` occasionally returns `x86_64` not `amd64` leading to `Platform not supported` runtime exceptions. Would supporting both values for mac os be feasible?

**Comment by wilsonzlin** [comment]
I've updated the Java library to also accept `x86_64` in version `0.3.9`, let me know if it works now.
