### ISSUE TITLE
PHP tag inside textarea is destroyed

### ISSUE THREAD

**Issue by zimbelstern** [wilsonzlin/minify-html#104]
`minify_html.minify("<textarea><?php ?></textarea>")`

results in

`<textarea>&LT?php ?></textarea>`

**Comment by winstonewert** [comment]
PHP isn't html, but a superset of it. Don't attempt to minify PHP with this tool.

**Comment by zimbelstern** [comment]
I'm do not attempt to minify PHP. I expect minify-html to simply ignore everything between `<?php` (or `<?=`) and `?>` and this works unless the tags are inside a textarea.

**Comment by winstonewert** [comment]
My bad, I didn't realize that PHP instructions should be recognized as processing instructions and thus work correctly.

**Comment by winstonewert** [comment]
See the documentation on [parsing](https://github.com/wilsonzlin/minify-html/blob/master/notes/Parsing.md#tags). <textarea>, <script>, and <title> tags are all defined to parse until finding the closing tag. That's presumably why it parses your <?php tag the way it does.

**Comment by wilsonzlin** [comment]
Thanks for raising, yes `<textarea>` and `<title>` element contents should be parsed in the [RCDATA state as per the spec](https://html.spec.whatwg.org/multipage/parsing.html#parsing-main-inbody), so all entities are decoded, but anything other than `</textarea`/`</title` is treated as literal character content and not special syntax. I've changed the behaviour in version `0.10.5`.
