### ISSUE TITLE
Time to tag a new release?

### ISSUE THREAD

**Issue by asb** [wilsonzlin/minify-html#105]
#90 fixes some easy to run into bugs (the README gives the example of `minify-html --keep-closing-tags --minify-css /path/to/**/*.html`). Perhaps it's time to tag a new release that includes this fix?

**Comment by Enter-tainer** [comment]
I'm also waiting for a new release. I currently use my self-built binary. 😇

**Comment by wilsonzlin** [comment]
Version `0.10.0` has just been released.
