### ISSUE TITLE
Removal of <head> could effect SEO

### ISSUE THREAD

**Issue by ArhanChaudhary** [wilsonzlin/minify-html#106]
Using minify-html, the bing url inspector tool is unable to detect the title and description meta tags. This could have a negative impact on SEO:
<img width="1202" alt="Screen Shot 2022-08-23 at 8 44 24 AM" src="https://user-images.githubusercontent.com/57512390/186207693-de92d901-e3a3-4c81-ae19-8aee874436f1.png">

Disabling minify-html, which adds back the <head> tag in the response, fixes these issues:
<img width="1199" alt="Screen Shot 2022-08-23 at 8 44 50 AM" src="https://user-images.githubusercontent.com/57512390/186207818-12e02f01-efa8-4085-8f5e-b567d3a23c53.png">
<img width="1201" alt="Screen Shot 2022-08-23 at 8 44 55 AM" src="https://user-images.githubusercontent.com/57512390/186207832-fb5c743b-9210-4d0e-8a6d-f21d1da79d0c.png">

**Comment by wilsonzlin** [comment]
You can use `keep_html_and_head_opening_tags` to keep the opening `head` tag.
