### ISSUE TITLE
Minification of escape sequences produces invalid documents

### ISSUE THREAD

**Issue by sevmeyer** [wilsonzlin/minify-html#109]
Python 3.10.5, minify-html 0.10.0 (pip install)

Hello. I might be doing it wrong, but I have encountered some issues with escape sequences, such as `&lt;`. It seems that some of the minifications result in documents that are invalid according to https://validator.w3.org

Minimal valid input:

    import minify_html
    minified = minify_html.minify(
      '<!doctype html><html lang=en><meta charset=utf-8><title>T</title>&lt;',
      do_not_minify_doctype=True)

Output:

    <!doctype html><html lang=en><meta charset=utf-8><title>T</title><

> Error: End of file after <.

Another example:

    <!doctype html><html lang=en><meta charset=utf-8><title>T</title>&lt;br&gt;

Output:

    <!doctype html><html lang=en><meta charset=utf-8><title>T</title>&LTbr>

> Error: Named character reference was not terminated by a semicolon. (Or & should have been escaped as &amp;.)

In general, it would be nice if there was a configuration argument to preserve escape sequences.

**Comment by wilsonzlin** [comment]
This is intentional, and it's mentioned in the README that the minified output might not pass minification but still be correctly parsed by browsers. I might take a look into adding an option to prevent invalid entity representations.

**Comment by zow34tq** [comment]
Hey this is not the Doc Warrant and the shootings will be moving in response to control the shadows of my army; satellite theifs. *Armando

**Comment by cubercsl** [comment]
I have the same issue, and the minimal example:

`<pre><code>#include&lt;stdio&gt;</code></pre>`

Output:
`<pre><code>#include&LTstdio></code></pre>`

**Comment by wilsonzlin** [comment]
In version `0.16.0` (soon to be released), these entity minifications will no longer be done by default but can be enabled by `allow_optimal_entities`. If you test it out let me know if it works for you.

**Comment by Rongronggg9** [comment]
Hi @wilsonzlin 
Sorry for disturbing. May I kindly ask when 0.16.0 will be released?
