### ISSUE TITLE
Support CSS pseudo classes without selector

### ISSUE THREAD

**Issue by Brixy** [wilsonzlin/minify-html#110]
Thanks a lot for your minifier!

If I am correctly informed using pseudo classes without selectors is valid CSS code, e.g. `:is()`.

Yet, `minify-html` produces wrong code breaking the whole CSS file if the asterisk is left out.

```
/* Original CSS (without `*` selector) */
:is(nav, .posts) a {
	text-decoration: none;
}
```

```
/* Minified CSS (error) */
:is(nav{text-decoration:none}
```

```
/* Original CSS (with `*` selector) */
:is(nav, .posts) a {
	text-decoration: none;
}
```

```
/* Generated CSS (correct) */
*:is(nav,.posts) a{text-decoration:none}
```

**Comment by wilsonzlin** [comment]
Thanks for raising, minify-html uses [css-minify](https://github.com/Mnwa/css-minify), I haven't investigated the example yet but it might be worth raising with the upstream as well.

**Comment by wilsonzlin** [comment]
It looks like the issue was resolved upstream, so I've bumped the version of css-minify, and the issue should be resolved in the next release.
