### ISSUE TITLE
Minify JSClosure returning a map minified improperly

### ISSUE THREAD

**Issue by M1ngXU** [wilsonzlin/minify-html#114]
`[0].map(n => ({a: n}))` is minified to `[0].map(n=>{a:n})` which produces an "unexpected :" error (the brackets shouldn't be removed).
Workaround:
`[0].map(n => {return{a: n}})`

(on Rust)

**Comment by wilsonzlin** [comment]
Thanks for raising this issue, it should be fixed in version `0.10.2`, let me know if it works for you.

**Comment by M1ngXU** [comment]
ok i’ll check it when i’m back home

**Comment by M1ngXU** [comment]
great, works!
