### ISSUE TITLE
not working with python 3.11

### ISSUE THREAD

**Issue by abdi-El** [wilsonzlin/minify-html#118]

**Comment by wilsonzlin** [comment]
This should be resolved by #117 and available in version 0.10.2.

**Comment by abdi-El** [comment]
I've tried to change the version 0.10.2 but it gives me errors with docker when I try to build the image with python 3.11

**Comment by wilsonzlin** [comment]
Sorry, meant to say 0.10.3, there hasn't been a release yet as we're blocked on https://github.com/actions/setup-python/issues/531.
