### ISSUE TITLE
/lib64/libc.so.6: version `GLIBC_2.18' not found Serverless

### ISSUE THREAD

**Issue by 1pavanb** [wilsonzlin/minify-html#12]
> Unable to import module 'handler': /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /var/task/minify_html.cpython-36m-x86_64-linux-gnu.so)

I'm running an Aws lambda function using serverless with DockerizePip=True

A quick search in google didn't fetch me any known fixes.

edit:
I've stopped using this, can't fix it.

**Comment by wilsonzlin** [comment]
It sounds like the GNU C library is missing. It might be located in a different place; try doing a root file search and updating `LD_LIBRARY_PATH`. If it's not installed, you'll probably need to install it. Some cursory Google searches did come up with very similar situations and potential solutions (note I haven't tested them myself):

https://bitsanddragons.wordpress.com/2018/04/11/importerror-lib64-libc-so-6-version-glibc_2-18-not-found-on-centos-7/
https://stackoverflow.com/questions/33655731/error-while-importing-tensorflow-in-python-2-7-in-ubuntu-12-04-glibc-2-17-not

If you need further help, provide more details such as the environment, how it was installed, Python version and path, etc.

**Comment by 1pavanb** [comment]
thanks for the help @wilsonzlin 
I'm too lazy to continue this issue.

I'm too unfamiliar with gnu c stuff.
I was using this minifier along with another one. It was working really fine outside of Aws lambda fn.
Although it was useful to optimize the email further, I'm happy even without this for now.

**Comment by nwparker** [comment]
For anyone having this on AWS (probably applies to Vercel too), then this issue is relevant pertaining to the included glibc version:
https://github.com/aws/aws-lambda-base-images/issues/59
