### ISSUE TITLE
ruby gem doesn't work on Silicon Mac

### ISSUE THREAD

**Issue by jeezs** [wilsonzlin/minify-html#120]
on silicon Mac with ruby 3.1.2 the gem crash : 
`dlopen(/Users/jean-ericgodard/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/minify_html-0.10.3/lib/macos-ruby3.1, 0x0009): tried: '/Users/jean-ericgodard/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/minify_html-0.10.3/lib/macos-ruby3.1' (no such file),`

**Comment by remino** [comment]
Hitting the same problem. Also running Ruby 3.1, on macOS 13.4.1.

Is this thing even supposed to work on Ruby anything more recent than 2.7 on macOS?

```
$ cd minify_html-0.10.8/lib/
$ ls
linux-ruby2.5
linux-ruby2.6
linux-ruby2.7
macos-ruby2.5
macos-ruby2.6
macos-ruby2.7
minify_html.rb
```

**Comment by wilsonzlin** [comment]
I've managed to get cross compilation working with Ruby. Version `0.11.3` has macOS ARM64 builds (and now also supports Ruby 2.7 to 3.2); if you are free to test it out please let me know if you encounter any issues.
