### ISSUE TITLE
pyo3_runtime.PanicException: byte index 4 is out of bounds of `#b`

### ISSUE THREAD

**Issue by jesusignaciob** [wilsonzlin/minify-html#121]
This exception is being thrown when minifying the following html, it seems to be when dealing with a colour.
[rust.txt](https://github.com/wilsonzlin/minify-html/files/10004972/rust.txt)

**Comment by wilsonzlin** [comment]
I'm not able to reproduce this issue, however it looks like the issue as described is related to CSS minification, so I've bumped the version of css-minify (the library minify-html uses for CSS minification) in the latest version `0.10.4`, let me know if it works on your end.
