### ISSUE TITLE
wasm compiled package.json should have `type: module`

### ISSUE THREAD

**Issue by SettingDust** [wilsonzlin/minify-html#122]
The compiled wasm module is esm. The package.json need `type: "module"` for use esm syntax. And the `module: "index.js"` should be `main: "index.js"`

**Comment by zow34tq** [comment]
Hey shut up bird. Fuck you. Grre illustrates a mac11 sub machine gun nests every 33 miles from target area Adelaide Albuquerque Amsterdam Atlanta Auckland Austin Baltimore Birmingham Boise ID number universal studios Hollywood.

I did that for free. Whatever
...

Stupud thiefs.

**Comment by wilsonzlin** [comment]
Thanks for raising, I've added `type` and `main` fields to the generated package.json. The official `wasm-pack` tool used for building the binary and generating the package doesn't appear to add these fields, so it may be worth raising upstream as well.

My understanding is that `module` is not an official field, and that adding `type` and `main` should allow importing from Node.js (although Node.js can't import WASM modules yet). However, as the primary use of the WASM variant package is for browsers, this should improve (or have no impact) on bundling.
