### ISSUE TITLE
Rust API slower than glob CLI

### ISSUE THREAD

**Issue by vallode** [wilsonzlin/minify-html#126]
Over at Zola (https://github.com/getzola/zola/issues/2031) I faced the issue of having my build slow down significantly when running with minify-html. It turned out that minification was being run on a _per file_ basis, rather than a batch job at the end of the build cycle.

Using the CLI version of minify-html I was able to include it after the build cycle, significantly improving my build process speed.

Is it possible to include a batch/glob capability to minify-html in the rust lib? Is there even a real difference between the implementation in the lib vs the cli?

**Comment by wilsonzlin** [comment]
There are no special optimisations for the CLI, it's simply processing files in parallel using [rayon](https://github.com/rayon-rs/rayon), which reduces total time taken if there are many. Per-file, it's calling the same APIs in the library and takes the same amount of CPU time. There is no special functionality for globbing either, as it simply takes the input files via argv (most likely, it's your shell that's expanding any globs).

If you're using the library API and want to process many files quickly, parallelism can help, using standard widely-used libraries like rayon, crossbeam, or std::thread and std::sync. As an example, refer to the [CLI source code](https://github.com/wilsonzlin/minify-html/tree/master/cli). I'm not aware of how zola implements or uses minify-html specifically.

**Comment by vallode** [comment]
Great. Thanks for writing that up. Clears things up greatly.
