### ISSUE TITLE
Rust: JS minification fails quietly

### ISSUE THREAD

**Issue by Carlrs** [wilsonzlin/minify-html#127]
When running minify with JS minification enabled and parse-js runs into an issue, nothing gets reported back, since the function returns a Vec<u8> rather than something like an Option<Vec<u8>>. Then I end up with a broken minified JS file and no knowledge that it's broken. Of course, the minify-js crate doesn't have this issue, but it'd be nice if I only needed to pull in one dependency, since there's functionality overlap.

**Comment by wilsonzlin** [comment]
Thanks for raising. If JS minification fails, there should be no broken output, as it simply outputs the original JS. Are  you able to provide the version you're using and some sample HTML to reproduce this issue?

I will look into adding an option to propagate errors in the result. Previously the library returned `Result<Vec<u8>>`, however this was disliked by many users who didn't want such strict processing of syntax. A good compromise I've been wanting to do for a while now is to still keep processing even on errors, but record them as warnings and provide them as well in the return value, so the minified code is still usable but you can decide whether or not to handle the warnings.

**Comment by Carlrs** [comment]
Actually, as it happens, I was trying to use minify_html directly on a javascript file, hoping/assuming it would work like that as well - so basically this was user error rather than an actual error with minify-html. To make matters worse, I literally had the minify JS disabled (using cfg::pec_compliant()) and the output was minified so I know know the JS minifier was never involved - must be why the single line comments were retained, in a single line file.

I'll just go back to using minify-js directly on standalone javascript files and minify-html only on actual HTML :) Closing this issue, because even the title is wrong. JS minification properly used through minify_html does actully not fail quietly - tested this out myself now.
