### ISSUE TITLE
'minifyHtml.minify is not a function'

### ISSUE THREAD

**Issue by jimasun** [wilsonzlin/minify-html#129]
win22H2 "@minify-html/node": "^0.10.7"

```
import * as minifyHtml from "@minify-html/node"

const minified = minifyHtml.minify(
    Buffer.from("<p>  Hello, world!  </p>"),
    {
        keep_spaces_between_attributes: true,
        keep_comments: true
    }
);
```

**Comment by wilsonzlin** [comment]
Thanks for raising, the import line should be:

```js
import minifyHtml from "@minify-html/node"
```

This is a typo in the README example. It does work from TypeScript with ESModule interop enabled, but doesn't work from a module script, as the functions are actually placed in the default export as an object. I've updated the README now.

**Comment by jimasun** [comment]
Previously I was getting the function resolved as I was hoovering on the method in vscode but it would not run it.

I have changed the code as you suggested and now I am getting another error. Are there other dependencies which I am not aware of? I am trying to use this tool in esbuild. `plugin esbuild-html-css-loader` is where I am running it from.

```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `PendingException`,
 right: `Ok`', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\neon-runtime-0.10.1\src\napi\error.rs:49:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
X [ERROR] internal error in Neon module: assertion failed: `(left == right)`
  left: `PendingException`,
 right: `Ok` [plugin esbuild-html-css-loader]
```

**Comment by wilsonzlin** [comment]
Upon first glance that looks like an upstream issue with the [Neon](https://github.com/neon-bindings/neon) library, can you raise an issue with them? If you can provide a sample HTML that triggers this, feel free to post it here and I'll try to reproduce and debug it from my end as well. Set `RUST_BACKTRACE=1` to output a Rust stacktrace when this occurs.

**Comment by jimasun** [comment]
Sure, I'll create a simple example. I haven't yet opened an issue at Neon, will wait for your response.

```
process.env['RUST_BACKTRACE'] = 'full'
return minifyHtml.minify(Buffer.from(`
    <div class="lower-buttons">
        <span class="next primary button disabled">Next</span>
    </div>`))
```

```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `PendingException`,
 right: `Ok`', C:\Users\runneradmin\.cargo\registry\src\github.com-1ecc6299db9ec823\neon-runtime-0.10.1\src\napi\error.rs:49:5
stack backtrace:
   0:     0x7fff51d21342 - napi_register_module_v1
   1:     0x7fff51d3245b - napi_register_module_v1
   2:     0x7fff51d1f8aa - napi_register_module_v1
   3:     0x7fff51d2108b - napi_register_module_v1
   4:     0x7fff51d230b9 - napi_register_module_v1
   5:     0x7fff51d22d3a - napi_register_module_v1
   6:     0x7fff51d23941 - napi_register_module_v1
   7:     0x7fff51d236cd - napi_register_module_v1
   8:     0x7fff51d21d6f - napi_register_module_v1
   9:     0x7fff51d23390 - napi_register_module_v1
  10:     0x7fff51d41475 - napi_register_module_v1
  11:     0x7fff51d317d4 - napi_register_module_v1
  12:     0x7fff51d403e0 - napi_register_module_v1
  13:     0x7fff51d19eb4 - napi_register_module_v1
  14:     0x7fff51c5114d - <unknown>
  15:     0x7fff51c52ced - napi_register_module_v1
  16:     0x7fff51c5225a - napi_register_module_v1
  17:     0x7fff51c52b93 - napi_register_module_v1
  18:     0x7ff6e4877100 - v8::internal::compiler::Instruction::Output
  19:     0x7ff6e528d35d - v8::internal::Builtins::code
  20:     0x7ff6e528cf69 - v8::internal::Builtins::code
  21:     0x7ff6e528d22c - v8::internal::Builtins::code
  22:     0x7ff6e528d090 - v8::internal::Builtins::code
  23:     0x7ff6e5371f81 - v8::internal::SetupIsolateDelegate::SetupHeap
  24:     0x7ff6e52f5894 - v8::internal::SetupIsolateDelegate::SetupHeap
  25:     0x7ff6e52f5894 - v8::internal::SetupIsolateDelegate::SetupHeap
  26:     0x7ff6e53299c3 - v8::internal::SetupIsolateDelegate::SetupHeap
  27:     0x7ff6e53c27b5 - v8::internal::SetupIsolateDelegate::SetupHeap
  28:     0x7ff6e531b0cc - v8::internal::SetupIsolateDelegate::SetupHeap
  29:     0x7ff6e52f3d9b - v8::internal::SetupIsolateDelegate::SetupHeap
  30:     0x7ff6e51be3ca - v8::internal::Execution::CallWasm
  31:     0x7ff6e51be4eb - v8::internal::Execution::CallWasm
  32:     0x7ff6e51bf29a - v8::internal::Execution::TryCallScript
  33:     0x7ff6e5197e6a - v8::internal::MicrotaskQueue::RunMicrotasks
  34:     0x7ff6e5197c0a - v8::internal::MicrotaskQueue::PerformCheckpointInternal
  35:     0x7ff6e48df288 - node::CallbackScope::~CallbackScope
  36:     0x7ff6e48df14e - node::CallbackScope::~CallbackScope
  37:     0x7ff6e4819fc7 - v8::base::CPU::has_fpu
  38:     0x7ff6e482ba51 - v8::internal::wasm::WasmCode::safepoint_table_offset
  39:     0x7ff6e4913c17 - uv_timer_stop
  40:     0x7ff6e49101bb - uv_async_send
  41:     0x7ff6e490f94c - uv_loop_init
  42:     0x7ff6e490faea - uv_run
  43:     0x7ff6e48deb15 - node::SpinEventLoop
  44:     0x7ff6e47e92c4 - std::basic_ios<char,std::char_traits<char> >::setstate
  45:     0x7ff6e486d058 - node::InitializeOncePerProcess
  46:     0x7ff6e486e895 - node::Start
  47:     0x7ff6e46874fc - CRYPTO_memcmp
  48:     0x7ff6e589fdd8 - v8::internal::compiler::ToString
  49:     0x7fff97d37614 - BaseThreadInitThunk
  50:     0x7fff986426a1 - RtlUserThreadStart
```

**Comment by jimasun** [comment]
I have raised an issue at Neon.

**Comment by kjvalencik** [comment]
Cross-posting the answer here: https://github.com/neon-bindings/neon/issues/959#issuecomment-1408619573

According to the source of `minify-html` the options object is _required_, but, the code provided is missing the 2nd argument. There's also a small error in the Rust when attempting to change the error message.

Let me know if there are any questions. Cheers!

**Comment by wilsonzlin** [comment]
Thanks @kjvalencik, I've updated the code to use `cx.try_catch`. Is this the preferred way of casting to a type, and using a different error message if it fails? I was thinking that `cx.argument` returns a pure Rust-like Result, but it sounds like it actually throws an exception (i.e. mutates internal state), so if there's a more idiomatic or faster way instead of `try_catch` please let me know.

@jimasun I've fixed the Node.js library to not cause the assertion failure panic in the latest version `0.10.8`, please let me know if it works on your end. Note that the second object is a required parameter, which is declared as such in the TypeScript definitions.

**Comment by jimasun** [comment]
Thank you, it works fine now and the error is clear about the second argument. 

`[ERROR] the second argument is not an object`

**Comment by wilsonzlin** [comment]
Thanks @kjvalencik, it sounds like using `try_catch` is fine so I'll leave it as is. I appreciate your detailed clarification of the Neon API and helping us out here.

**Comment by jimasun** [comment]
I would suggest to make the `options` optional since it is more clean rather than providing an empty `{}` object.
