### ISSUE TITLE
SyntaxError: Closing tag name does not match opening tag

### ISSUE THREAD

**Issue by 1st** [wilsonzlin/minify-html#13]
I've such error when running minifier.

```
SyntaxError: Closing tag name does not match opening tag (expected "div", got "span")
```

Can I pass a tag that it's okay to minify data without validation of the closing tags? I can't control the input source of the content and can't normalise it, but need to minify it. Is it possible to pass some flag to the library to skip such errors?

**Comment by wilsonzlin** [comment]
minify-html needs to have strict guarantees about input as it overwrites memory in place, so it currently does require stricter syntax than, say, a browser. The HTML spec does define all cases, but handling edge cases can become very complex and decrease maintainability and speed for little gain.

I would be interested in looking into it a bit more detail though. In this specific case, what should the expected logic/output be?

**Comment by 1st** [comment]
Oh, sorry to miss the original answer. The problem is that it’s no guarantee that some external libraries or templates we use have the correct html output. But I did my own solution that compresses faster 20-40x times, compress better a little, and does not care about html validity. So, we switched to my own solution at the moment of writing the original bug report.

**Comment by njzjz** [comment]
I encounter the same error and use `try...except` to skip the error.

```py
try:
    return minify_html_onepass.minify(
        content, minify_js=True, minify_css=True
    )
except SyntaxError:
    return content
```
