### ISSUE TITLE
Useful empty `href` attribute being dropped incorrectly

### ISSUE THREAD

**Issue by Equim-chan** [wilsonzlin/minify-html#130]
In this case, `href=""` is essential for this `a` tag to be clickable, and neither `href="."`, `href="#"` or ` ` can replace its function.

```rust
use minify_html::{minify, Cfg};

fn main() {
    let src = r#"<a href="" download>Save this page</a>"#;
    let minified = minify(src.as_bytes(), &Cfg::default());
    println!("{}", String::from_utf8_lossy(&minified));
}
```

Output:

```plain
<a download>Save this page</a>
```

Version:
0.10.7

**Comment by wilsonzlin** [comment]
Thanks for raising, I've just fixed this in version `0.10.8`, let me know if it works on your end.
