### ISSUE TITLE
CSS compress Changed the effect

### ISSUE THREAD

**Issue by TakWolf** [wilsonzlin/minify-html#132]
call in python

minify_html=0.10.8

```python
import minify_html
    
html = minify_html.minify(html, minify_css=True, minify_js=True)
```

Raw html:

See demo https://static.takwolf.com/github/minify-html/normal.html

```html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title></title>
    <style>
        @keyframes background-scrolling {
            100% {
                background-position: 128px 128px;
            }
        }
        body {
            background-color: #3cb03c;
            background-image: linear-gradient(45deg, limegreen 25%, transparent 25%, transparent 75%, limegreen 75%), linear-gradient(-45deg, limegreen 25%, transparent 25%, transparent 75%, limegreen 75%);
            background-size: 128px 128px;
            background-attachment: fixed;
            animation: background-scrolling 4s infinite linear;
        }
    </style>
</head>
<body>
</body>
</html>

```

Output html: (has been reformated)

See demo https://static.takwolf.com/github/minify-html/error.html

```html
<!doctypehtml>
<html lang=zh>
<meta charset=UTF-8>
<meta content=width=device-width,initial-scale=1 name=viewport>
<title></title>
<style>
    @keyframes background-scrolling {
        100% {
            background: 128px 128px
        }
    }
    body {
        animation: background-scrolling 4s infinite linear;
        background: #3cb03c;
        background-size: 128px 128px
    }
</style>
<body>
```

**Comment by TakWolf** [comment]
Related https://github.com/wilsonzlin/minify-html/issues/89

**Comment by TakWolf** [comment]
It seem that `background-color` replace `background-image`,  but them should be set both. 

https://css-tricks.com/css-basics-using-multiple-backgrounds

**Comment by wilsonzlin** [comment]
Thanks for raising, this looks like an issue with the [upstream CSS minifier](https://github.com/Mnwa/css-minify), can you also open an issue there? Keep this issue open as well for tracking and awareness.

**Comment by TakWolf** [comment]
As #89 say:

> While css-minify provides three levels of optimization and [defaults to 1](https://github.com/Mnwa/css-minify/blob/master/css-minify/Readme.md?plain=1#L57), minify-html hardcodes Level::Three.

As [CSS minifier](https://github.com/Mnwa/css-minify) readme:

```
   2 - Level One + shortcuts (margins, paddings, backgrounds and etc).
                             In mostly cases it's non dangerous optimizations, but be careful
```

Test on https://css-minify.panfilov.tech

It cause incorrect when set level is 2, level 1 is ok.

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/6064962/219293078-78c14d8e-e687-4bd6-8310-4bfc6ad598fc.png">

I'm not sure if it was a bug for css-minify

**Comment by wilsonzlin** [comment]
It's a good point. I think it should be considered a bug if a minifier (or any optimiser) changes the execution behaviour from the source according to the spec; if it's not possible to keep it the same, it should leave it alone. Otherwise, it goes against its purpose (as it's no longer optimising the input program/logic but some other arbitrary one), and the best minifier/optimiser is one that just returns nothing.

However, given the upstream minifier's optimisation level safety, I will change the default setting to One and add `Cfg` fields for using a different level.

**Comment by TakWolf** [comment]
minify-html = 0.10.8 (css-minify=0.3.1)    optimization=1

input:
```
        .some-effect :lang(zh) {
            color: blue;
        }
```

output:
```
.some-effect:lang(zh){color:blue}
```

They are not equivalent.

```html
<div class="some-effect">
    <span lang="zh">
            Only valid in case 1
    </span>
</div>
```

```html
<div class="some-effect" lang="zh">
Only valid in scenario 2
</div>
```




minify-html = 0.10.3 (css-minify=0.2.2)   

No problem about this.

**Comment by wilsonzlin** [comment]
An update: I've replaced css-minify with lightningcss in version `0.13.0`. If this issue still occurs please reopen this issue.
