### ISSUE TITLE
Add option to disable removing `type="text"` on `<input>` elements

### ISSUE THREAD

**Issue by susheel61** [wilsonzlin/minify-html#134]

**Comment by susheel61** [comment]
`input type="text" is getting removed`

**Comment by wilsonzlin** [comment]
This is intentional, see https://github.com/wilsonzlin/minify-html/issues/95#issuecomment-1207136042 for more details.

**Comment by susheel61** [comment]
Is there a way to edit it because I already of css on input text type

**Comment by wilsonzlin** [comment]
I'll investigate adding an option to disable minification for `input[type=text]` specifically.

**Comment by susheel61** [comment]
Thanks I tried to contribute but didn't find any specific java code so was confused. Anyways thanks for taking this up.

**Comment by mumashanren** [comment]
Yes, many css will use `input[type=text]`, hopefully support will be provided.

**Comment by wilsonzlin** [comment]
I've added an option `keep_input_type_text_attr` in version `0.15.0` to preserve `type=text` attributes on `<input>` elements.
