### ISSUE TITLE
argument list too long

### ISSUE THREAD

**Issue by fabriziogiordano** [wilsonzlin/minify-html#137]
I am building an AstroJS website.

When I run:
```
./minify-html --keep-closing-tags --minify-css --minify-js ./astro/build/**/*.html
```

I get this error:
```
zsh: argument list too long: ./minify-html
```

There are about 65,000 html files in the build folder.

Instead of the cli version, should I use some other wrapper?

**Comment by DiegoYungh** [comment]
That looks like the case for a folder/file traverser and feed the minify script with chunks

**Comment by wilsonzlin** [comment]
The CLI should be fast enough. If there are too many files for the CLI, perhaps feeding files as lines into something like `parallel` could work:

```bash
ls -1 ./astro/build/**/*.html | parallel -m ./minify-html --keep-closing-tags --minify-css --minify-js '{}'
```

The `-m` arg to `parallel` will put as many args as can fit in one invocation, to minimise the amount of process executions. `parallel` will itself then run them in parallel. The official [parallel docs](https://www.gnu.org/software/parallel/parallel_examples.html#example-inserting-multiple-arguments) actually mention the "argument list too long" error as a good use case.
