### ISSUE TITLE
request for apple silicon support

### ISSUE THREAD

**Issue by BycorSanchez** [wilsonzlin/minify-html#138]
I attempted to minify html code but it seems that apple silicon is not supported yet. Using Java version 0.10.8.

I'd be grateful if this were possible to develop. Thanks!

Error message:

Caused by: java.lang.RuntimeException: Platform not supported (os.name=mac os x, os.arch=aarch64)
	at in.wilsonl.minifyhtml.MinifyHtml.<clinit>(MinifyHtml.java:31)

**Comment by wilsonzlin** [comment]
I've managed to get cross compilation working for the CLI, Python, Ruby, and Node.js, so those now have builds for macOS ARM64. The only one left is Java, which I will look at today.

**Comment by wilsonzlin** [comment]
The Java library version `0.13.3` now comes with macOS and Linux ARM64 builds. Let me know if it works for you.

**Comment by BycorSanchez** [comment]
Just tested version 0.15.0. It works smoothly.

Thanks for your time!
Merry xmas by the way.
