### ISSUE TITLE
HTML entities replaced by reserved characters in output HTML

### ISSUE THREAD

**Issue by blueglyph** [wilsonzlin/minify-html#139]
## Problem

HTML entities like `&lt;` and `&gt;` are replaced by their equivalent reserved characters (`<` and `>`), producing a corrupted output HTML file.

## Steps

Launching the executable with the parameters `-o index_minified.html index.html`, with the index.html content below:

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
    <title>Test</title>
</head>
<body>
    
<p>
    Pages: <a class="disabled" href=''>&lt;</a>
    <a class="disabled" href='http://192.168.1.38:1111'>1</a>
    <a href='http://192.168.1.38:1111/page/2'>&gt;</a>
</p>

    <footer>
        <span class="copyright">Copyright 2023 by AUTHOR.</span><br>
        <span class="zola">Made with <a href="https://www.getzola.org/">Zola</a></span>
    </footer>
</body>
</html>
```

produces the following:

```html
<!doctypehtml><html lang=en><meta charset=UTF-8><meta content=width=device-width,initial-scale=1,maximum-scale=1 name=viewport><title>Test</title><body><p>Pages: <a class=disabled href><</a> <a class=disabled href=http://192.168.1.38:1111>1</a> <a href=http://192.168.1.38:1111/page/2>></a><footer><span class=copyright>Copyright 2023 by AUTHOR.</span><br><span class=zola>Made with <a href=https://www.getzola.org/>Zola</a></span></footer>
```

in which you can see those two errors: `<a class=disabled href><</a>` and `<a href=http://192.168.1.38:1111/page/2>></a>` corresponding to lines 11 and 13 of the original file (as attachment: [index.zip](https://github.com/wilsonzlin/minify-html/files/11200904/index.zip))

I haven't tested other HTML entities.

## Environment

CLI version 0.10.8 (Windows 10 x64), or with Zola as Rust crate version 0.10.8.

**Comment by wilsonzlin** [comment]
This is intentional, as mentioned in the [README](https://github.com/wilsonzlin/minify-html#minification). It will still be parsed correctly by the browser, which allows some extra compression. This is only done when safe, so there shouldn't be any misinterpretation.

**Comment by blueglyph** [comment]
I missed that part, "will not pass validation". Isn't that a gamble on how the different engines parse HTML (and whether they'll continue to do so)?

I can't reproduce the corrupted pages I got, so maybe I had another issue, but I'm definitely not comfortable with it. I have tried with the `--ensure-spec-compliant-unquoted-attribute-values` option (in the latest Windows binary) but it didn't make any difference, is there any other way to avoid it?

**Comment by wilsonzlin** [comment]
The behaviour is defined as part of the HTML WHATWG spec as noted in the [13.2.5.6 Tag open state](https://html.spec.whatwg.org/multipage/parsing.html#tag-open-state) rules, so browsers and any other spec-compliant parser handle it correctly, and it's not undefined behaviour. Browsers have well-defined behaviour for consistency and compatibility reasons, including for handling not well formed HTML. I may take a look into adding an option to disable this specific minification.

**Comment by blueglyph** [comment]
That's interesting, thanks!

If it's safe, no need for an additional option. It's easy enough to filter out those "issues" in the validator logs. 🙂

**Comment by wilsonzlin** [comment]
In version `0.16.0` (soon to be released), these entity minifications will no longer be done by default but can be enabled by `allow_optimal_entities`. If you test it out let me know if it works for you.
