### ISSUE TITLE
`@minify-html/node` post install script does not verify checksum of downloaded binaries

### ISSUE THREAD

**Issue by lopopolo** [wilsonzlin/minify-html#145]
There was recently a malware incident in the popular `fsevents` package due to pre-compiled binaries in a cloud storage bucket being tampered with after the package was published: https://github.com/advisories/GHSA-xv2f-5jw4-v95m.

A similar risk exists with this package. GitHub releases are mutable and the binaries stored in them could be swapped out post-publishing.

Would you consider embedding something like a SHA256 or SHA512 checksum for each platform in `postinstall.js` and verifying that the downloaded pre-built artifacts match the published versions expectations?

**Comment by wilsonzlin** [comment]
Thanks for raising this, this is a great idea, I've implemented this and it will be part of the next release. The SHA-512 checksums are generated at build time and bundled as part of the npm package. The script in the package that downloads from the remote server will compare the downloaded binary's checksum to the checksum stored in its package, and throw an error if they don't equal.
