### ISSUE TITLE
macOS Apple Silicon wheels?

### ISSUE THREAD

**Issue by akx** [wilsonzlin/minify-html#147]
It seems the Mac wheels on PyPI are x86_64 only – I'd appreciate Apple Silicon (or universal2) wheels too :)

The package does seem to build just fine on Apple Silicon, so I suppose this would just need some adjustments to the CI pipeline.

**Comment by wilsonzlin** [comment]
I've managed to get cross compilation working with Python. Version `0.11.3` has macOS ARM64 builds; if you are free to test it out please let me know if you encounter any issues.
