### ISSUE TITLE
The aarch64 Python wheels of v0.11.1 require a fairly new libc version v2.34

### ISSUE THREAD

**Issue by Rongronggg9** [wilsonzlin/minify-html#149]
This breaks the compatibility of the pre-built wheel on Ubuntu<=20.04, Debian<=11, etc.

**Comment by wilsonzlin** [comment]
Thanks for raising, this should be resolved with version `0.11.3` and greater as it now uses the standard manylinux containers to cross compile instead of compiling on the host. If you're free to test this out let me know if you encounter any issues.
