### ISSUE TITLE
Feature Request: Add support for SSI comments

### ISSUE THREAD

**Issue by Jared-Sprague** [wilsonzlin/minify-html#151]
Hello!

We are using Server Side Includes, which is a [standard](https://www.w3.org/Jigsaw/Doc/User/SSI.html#include) that is used by many [web servers](https://en.wikipedia.org/wiki/Server_Side_Includes) such as [Apache SSI](https://httpd.apache.org/docs/2.4/howto/ssi.html). 

The problem is that these are formatted as HTML comments, so the minifyer strips them out, because we want to strip out HTML comments but we want to leave SSI comments because they are important.

So the request is: Can you add support for SSI standard comments, to leave them in place, while stripping out other HTML comments?

**Comment by wilsonzlin** [comment]
Thanks for this suggestion, I've implemented this in version `0.12.0` as the `keep_ssi_comments` option, let me know if it works for you.
