### ISSUE TITLE
Firefox rejects minified CSS due to `:placeholder`

### ISSUE THREAD

**Issue by penn5** [wilsonzlin/minify-html#154]
Using a CSS selector `#a::placeholder` as used in text inputs, the selector is rejected if minified to `#a:placeholder`, so this optimisation should be disabled. My CSS optimisation is set to level 1.

**Comment by wilsonzlin** [comment]
Thanks for raising this, I've replaced css-minify with lightningcss in version `0.13.0`, let me know if this issue still occurs. [lightningcss](https://github.com/parcel-bundler/lightningcss) is much more developed and should have fewer correctness issues.
