### ISSUE TITLE
How to use with wrangler by cloudflare

### ISSUE THREAD

**Issue by damianslayer** [wilsonzlin/minify-html#156]
How to use with wrangler ?

**Comment by wilsonzlin** [comment]
AFAIK Wrangler is a Cloudflare CLI for Workers. Can you clarify what you are looking to do? If you want to use this library from a Worker, I believe you'll need the WASM variant, as I don't think the Workers runtime supports native Node.js modules.

**Comment by rmarscher** [comment]
I was able to get `@minify-html/wasm` working on Cloudflare workerd runtime (using wrangler to run it locally). 

The index.js created by wasm-bindgen needs to be patched. I edited node_modules/@minify-html/wasm/index.js to be this:

```js
import * as imports from "./index_bg.js"

// switch between both syntax for node and for workerd
import wkmod from "./index_bg.wasm"
import * as wasm from "./index_bg.wasm"
if (typeof process !== "undefined" && process.release.name === "node") {
  imports.__wbg_set_wasm(wasm)
} else {
  const instance = new WebAssembly.Instance(wkmod, { "./index_bg.js": imports })
  imports.__wbg_set_wasm(instance.exports)
}

export * from "./index_bg.js"
```

And then I could import and use the minify function normally from my project.

```js
import { minify } from "@minify-html/wasm"

const html = "<p>\n    Some HTML\n</p>\n\n\n"
const encoder = new TextEncoder()
const decoder = new TextDecoder()

decoder.decode(
  minify(encoder.encode(html), {
    keep_spaces_between_attributes: true,
    keep_comments: true,
  }),
)
```

This section of the cloudflare docs mentions that workaround. https://developers.cloudflare.com/workers/languages/rust/#javascript-plumbing-wasm-bindgen
