### ISSUE TITLE
Missing sdist on PyPI for 0.11.2

### ISSUE THREAD

**Issue by mgorny** [wilsonzlin/minify-html#165]
The [0.11.2 release on PyPI](https://pypi.org/project/minify-html/0.11.2/#files) has prebuilt wheels only but lacks the source archive. Please upload it.

**Comment by ajslater** [comment]
an osx aarch64 wheel would be nice too, but it is easily buildable with an sdist.

**Comment by wilsonzlin** [comment]
@mgorny The sdist has been published with the latest version `0.11.3` and onwards.

@ajslater I've managed to get cross compilation working with Python. Version `0.11.3` has macOS ARM64 builds; if you are free to test it out please let me know if you encounter any issues.
