### ISSUE TITLE
Python 3.9 support

### ISSUE THREAD

**Issue by romainthomas** [wilsonzlin/minify-html#18]
Hello, 
Thanks for this project, would it be possible to add Python 3.9 support ?

**Comment by zinootje** [comment]
#19

**Comment by gfiorav** [comment]
Hi,

First of all, thanks for creating and maintaining this amazing library! Also, happy new year.

I was wondering if @wilsonzlin might release a new version of this library to PyPI with support for 3.9? I've seen the proposed patch was merged in #19. I'm developing on an M1 Mac and it's the only version of Python I can use at the moment. 

Thanks in advance!

**Comment by wilsonzlin** [comment]
I just made a release with a build for Python 3.9 and macOS 11, version `0.3.12`, let me know if it works for you. I have noticed some issues around Big Sur and Apple Silicon, so would be interested to hear your experience with the package.

**Comment by romainthomas** [comment]
@wilsonzlin The new release works well from my side

**Comment by gfiorav** [comment]
Thanks @wilsonzlin! It will probably be a few days before I have any actionable feedback, but consider no news as good news.

Thanks again for putting this together!

**Comment by gfiorav** [comment]
Tried it out for a bit and all seems to work as intended. Things I tried:

- minify with `minify_js=True`

**Comment by wilsonzlin** [comment]
🎉 Sounds good, closing this issue.
