### ISSUE TITLE
Not Purging JS Comments

### ISSUE THREAD

**Issue by sno2** [wilsonzlin/minify-html#20]
Hello, thank you for your library.  I built a [minifier module for Deno](https://deno.land/x/minifier) and this library has worked great until I realized this problem.  When I try to minify the following js code:

```js
// hello

const x = 23;

for (let i = 0; i < 23; i++) {
  console.log(x);
}
```

I am getting the following:
```js
// hello const x = 23; for (let i = 0; i < 23; i++) { console.log(x); }
```

However, this should be purging the comments, instead.

I am able to reproduce this behavior with the following rust code:

```rust
pub fn minify_html(code: String, minify_css: bool, minify_js: bool) -> String {
  String::from(
    std::str::from_utf8(
      minify_html::copy(
        code.as_bytes(),
        &minify_html::Cfg {
          minify_css,
          minify_js,
        },
      )
      .unwrap()
      .as_slice(),
    )
    .unwrap(),
  )
}

pub fn main() {
  let minified = minify_html(
    String::from(
      r##"// hello

const x = 23;

for (let i = 0; i < 23; i++) {
  console.log(x);
}"##,
    ),
    false,
    true,
  );
  println!("{}", minified);
}
```

Is there something that I am doing wrong, or is this a problem with the library?  Thanks

**Comment by wilsonzlin** [comment]
The script code is being interpreted as HTML text, which is why it didn't remove the comment or spaces around identifiers. You can place the JS in a `<script>` tag to see the JS minification, but there's no way to directly minify JS as this is a HTML minification library. It uses [esbuild-rs](https://github.com/wilsonzlin/esbuild-rs) so that can be used for JS minification if desired.

**Comment by sno2** [comment]
> The script code is being interpreted as HTML text, which is why it didn't remove the comment or spaces around identifiers. You can place the JS in a `<script>` tag to see the JS minification, but there's no way to directly minify JS as this is an HTML minification library. It uses [esbuild-rs](https://github.com/wilsonzlin/esbuild-rs) so that can be used for JS minification if desired.

Oh, lol.  Sorry for bothering you.  I thought that it had automatically inferred the language as either HTML, CSS, or JS.  Thanks

**Comment by sno2** [comment]
@wilsonzlin Would it not be better if it left `script` and `link` tags alone just like the `pre` and `code` tags?

**Comment by rien333** [comment]
So, if I understand correctly, the `minify-html` binary that this project ships _can_ minify CSS and JS, but will only do so if it's wrapped in `<style>`/`<script>`?
