### ISSUE TITLE
New Java Version

### ISSUE THREAD

**Issue by webfolderio** [wilsonzlin/minify-html#23]
Hi,

Could you please update the Java library to the latest version, 0.4.3
Current maven central version is [0.4.1](https://search.maven.org/artifact/in.wilsonl.minifyhtml/minify-html)

Thanks

**Comment by wilsonzlin** [comment]
I've just published the latest version `0.4.5` to Sonatype OSSRH, it should be available now. An expired key was the cause of the delay in publishing for Java versions.

**Comment by webfolderio** [comment]
Thanks!
