### ISSUE TITLE
wasm

### ISSUE THREAD

**Issue by alexander-akait** [wilsonzlin/minify-html#24]
What do you think about shipping wasm version? Will be useful for Node.js and browsers users?

**Comment by dhardtke** [comment]
I second this as it would allow to support both [NodeJS](https://nodejs.org/api/wasi.html) replacing the current node bindings as well as [Deno](https://deno.land/manual/getting_started/webassembly).

**Comment by wilsonzlin** [comment]
Previously, using esbuild required using C-based FFI and was difficult (if not impossible) to try and build towards other targets, like WASM.

In the latest version `0.9.0`, esbuild has been replaced with [minify-js](https://github.com/wilsonzlin/minify-js), a JS minifier I wrote from scratch fully in Rust, so now it should be able to target any platform that Rust supports. As such, there are now WASM and Deno variants available 🎉 

If you try out either, let me know if it works on your end.
