### ISSUE TITLE
Generates invalid output when we have a multi-word string attribute followed by another attribute

### ISSUE THREAD

**Issue by reivilibre** [wilsonzlin/minify-html#27]
Example:

```
oli@bbm-neon:/tmp$ cat html.html 
<img src="blah.png" alt="quail picture" width="42">

<blah wombat="this has a space in it" spqr="aa"></blah>
oli@bbm-neon:/tmp$ minify-html-0.4.3-linux-x86_64 -s html.html 
<img src=blah.png alt="quail picture"width=42><blah wombat="this has a space in it"spqr=aa></blah>
```

Firefox's view-source and the W3C validator choke on this;

> Error: No space between attributes.
> At line 1, column 4111
> `ed on a branch"width=246 heigh`

**Comment by wilsonzlin** [comment]
This is expected behaviour as documented, as browsers will still parse and interpret/render it correctly despite being invalid HTML. Are you looking to turn off this specific functionality?

**Comment by reivilibre** [comment]
Hmm, I suppose I wasn't expecting it to give me invalid HTML — I can't see that in the README, even looking now; not sure where it is documented. I guess I would say it is 'surprising'.

I feel a little bit icky about contributing to the set of websites with invalid HTML, but I suppose everything venturing out onto the wild web needs to be able to handle it anyway… so hmm, kind of on the fence about that one...

In my case, I'm not using your library directly, but using Zola.

Maybe I can see it being sensible to have the option to generate spec-compliant HTML even at the expense of a few of these little optimisations, but I suppose it's no big deal; I didn't realise this was expected, that's all, and I suppose I'm happy to live with it.

**Comment by wilsonzlin** [comment]
Good point, it's not mentioned that the output can be invalid HTML, I'll add something to the README. This specific feature is documented as "Spaces are removed between attributes if possible". It should be harmless outside of HTML validators, and was inspired by [other minifiers](https://github.com/kangax/html-minifier).

There have been others who want similar ability to toggle specific features which I am looking into. However in your case I'm not sure how it'd work from Zola; a possible way would be for the Zola CLI to have additional options specific to HTML minification. It sounds like a "standards-compliant" option would be nice to have.

**Comment by NieDzejkob** [comment]
This is NOT harmless. I just tracked down a very annoying bug, in that Feedbro wasn't detecting my feed. As it turns out, they ship a custom parser that chokes on this if this optimization triggers within the `<link>` tag.
