### ISSUE TITLE
Where is  the closing tag?  Is there anyway to keep the closing tag?

### ISSUE THREAD

**Issue by darkdarkfruit** [wilsonzlin/minify-html#28]
From the doc, I see certain tags could be omitted, but is there anyway to keep the closing tag as some old browser will treat them as invalid html.
```rust
use minify_html::{Cfg, Error, copy};

let mut code: &[u8] = b"<p>  Hello, world!  </p>";
let cfg = &Cfg {
    minify_js: false,
    minify_css: false,
};
match copy(&code, cfg) {
    Ok(minified) => {
        assert_eq!(code, b"<p>  Hello, world!  </p>");  // <--- Where is  the closing tag?
        assert_eq!(minified, b"<p>Hello, world!".to_vec()); // ditto
    }
    Err(Error { error_type, position }) => {}
};
```

**Comment by reivilibre** [comment]
Which browsers will parse that as invalid HTML? As far as I know, `p` is allowed to have the ending tag left off according to the spec.

**Comment by wilsonzlin** [comment]
There is currently no way to turn off specific minification features such as tag omission, but I'm looking into exposing this through `Cfg`.

**Comment by darkdarkfruit** [comment]
That will be very nice.
