### ISSUE TITLE
Leaves hanging process in Node.js

### ISSUE THREAD

**Issue by igregson** [wilsonzlin/minify-html#29]
Recently switched to minify-html and noticed my system's fan coming on after stopping the "develop" process in my project. After a good bit of digging, I found that minify-html leaves a hanging CPU process. The only way to stop it is to force quit it (via the Activity Monitor app).

I've created a minimal reproduction case here: https://github.com/igregson/minify-html-test (with relevant notes in the README).

Note that simply requiring the package causes the bug (it doesn't actually have to be executed).

**Comment by igregson** [comment]
Forgot to leave my system and other relevant details:

Device: Macbook Pro (2016)
OS: Big Sur v11.2.3

Node: v14.16.0
NPM: 6.14.10

**Comment by wilsonzlin** [comment]
Thanks for the details and test case. I was able to reproduce the behaviour on my macOS desktop, as well as in another project indepdently.

I have published `@minify-html/core`, which does not have a JS/CSS minifier included, and does not have this issue. From a quick initial look, this issue might be quite difficult to fix in `@minify-html/js` as it seems to be related to how signals are handled by the cgo runtime (needed for the bundled esbuild) and whatever program is using the library (in this case, Node.js). This can be seen by doing a trace of system calls when SIGINT is sent; it seems from some cursory research that the Go runtime does not cleanly coexist with other code that also handles signals.

I'll continue to take a look into the issue. One possible solution that I'm investigating is to port the esbuild transform function to Rust code so the complexities and issues with FFI, cgo, libraries etc. can go away.

**Comment by wilsonzlin** [comment]
In the latest version `0.9.0`, esbuild has been replaced with [minify-js](https://github.com/wilsonzlin/minify-js), a JS minifier I wrote from scratch fully in Rust, so there should no longer be any issues similar to what you've described. Note that it's a minor version update so there are small but breaking changes for the Node.js package. Let me know if it works on your end.
