### ISSUE TITLE
Entities in double quotes should not be replaced

### ISSUE THREAD

**Issue by dohvis** [wilsonzlin/minify-html#33]
```python
html = """
<a href="example.com?a=b&params=1" />
"""
minify(html)
# '<a href=example.com?a=b¶ms=1 />'
```
&param -> `¶m`

**Comment by wilsonzlin** [comment]
Thanks for raising, I found the [obscure part of the spec](https://html.spec.whatwg.org/multipage/parsing.html#named-character-reference-state) where this is described and have implemented its behaviour in version `0.4.10`. I just tested it on the input provided and it works correctly now.

To be specific, it's not all entities; rather, it's named entities that don't end with a semicolon but are followed by an alphanumeric or `=` character.
