### ISSUE TITLE
exception raised on optional closing img tag (</img>)

### ISSUE THREAD

**Issue by ignatiusab** [wilsonzlin/minify-html#35]
Hey, I guess I found a bug.

I am aware that there is no closing tag for `<img>` . However, people keep includes them in and browsers can handle that with no issues. Thus I think it should be taken into consideration when running the minifier.

minify-html version `4.10`
python 3

```python
minify("<img ></img >", minify_js=True, minify_css=True)
# SyntaxError: Unexpected closing tag. [Character 6]

# While this is fine and produces correct result
minify("<img />", minify_js=True, minify_css=True) == "<img>"
```
expected result:
 `<img ></img >` should be minified to `<img>` by removing the closing tag.

**Comment by wilsonzlin** [comment]
This has been implemented as of version `0.5.0`. Closing void tags are now simply ignored. The parser can now handle all possible inputs and will never return/throw an error.

Note that `0.5.0` is a breaking change from `0.4.x`, but API changes are minor. The Python library should have no breaking API changes.

Let me know if it works for you.
