### ISSUE TITLE
textarea newlines not respected

### ISSUE THREAD

**Issue by tbillington** [wilsonzlin/minify-html#37]
When using `minify-html = "0.4.10"` from cargo, newlines in `<textarea>` elements are collapsed, altering the content.

Eg, rendering the string `a\r\nb` inside a text area:

```html
<textarea>a
b</textarea>
```

which renders like 
![image](https://user-images.githubusercontent.com/2771466/118398312-6247f080-b69b-11eb-8c82-58c60e99518b.png)

when minified is transformed to the html

```html
<textarea>a b</textarea>
```

which renders like this

![image](https://user-images.githubusercontent.com/2771466/118398374-a1764180-b69b-11eb-916c-f81891594250.png)

**Comment by tbillington** [comment]
I think textarea should probably be treated like `code` or `pre`.

This minifier implementation has something similar: https://github.com/martingallagher/html5minify/blob/master/src/lib.rs#L654

**Comment by wilsonzlin** [comment]
Good point, I've made `<textarea>` a whitespace-sensitive tag. This is fixed in version `0.4.11`.

**Comment by tbillington** [comment]
Awesome, feel free to close :)
