### ISSUE TITLE
Question: Is there plan to create package for PHP?

### ISSUE THREAD

**Issue by sandyandi** [wilsonzlin/minify-html#38]
Since PHP is still a widely used language for the web, many PHP websites that put performance as top priority, such as e-commerce and SEO-heavy websites, will benefit from this package.

There's currently no html minifier in PHP that's as fast as this one.

**Comment by wilsonzlin** [comment]
I did investigate initially, but couldn't find any easy developed way to make a native extension for PHP via Rust. I'm definitely interested though. I'll continue watching the space and monitoring developments.
