### ISSUE TITLE
Further minify CSS?

### ISSUE THREAD

**Issue by murty2** [wilsonzlin/minify-html#39]
Further minify CSS? For example

`style="font-family: serif;"`

to:

`style="font-family:serif"`

That is, remove spaces after colon (:) and semi-colon (;) just before closing single/double quote.

**Comment by allan2** [comment]
That would be helpful for me too.
The space after the colon is more commonly removed and the trailing semicolon less so.
Perhaps leave the choice to the caller?

**Comment by wilsonzlin** [comment]
This has been implemented as of version `0.5.0`. `style` attribute values will be minified as CSS if `cfg.minify_css` is true.

Note that `0.5.0` is a breaking change from `0.4.x`, but API changes are minor. It may have not changed at all depending on the language variant.

Let me know if it works for you.
