### ISSUE TITLE
No matching distribution for Apple M1

### ISSUE THREAD

**Issue by zhanymkanov** [wilsonzlin/minify-html#45]
I can't install it via `pip install minify-html` for M1 processor.
```
ERROR: Could not find a version that satisfies the requirement minify-html (from versions: none)
ERROR: No matching distribution found for minify-html
```
The only take away is to `export DOCKER_DEFAULT_PLATFORM=linux/amd64`. 

Do you have plans on supporting the M1 processors? That would be so great, since that is the only library that forces me to change the docker platform (which makes builds way slower)

**Comment by wilsonzlin** [comment]
I've added support for Python on macOS ARM64 with version `0.7.0`, let me know if it works for you.

**Comment by zhanymkanov** [comment]
Just tested it, works great!

Thank you!

**Comment by hishamkaram** [comment]
@wilsonzlin Hi, does this supports python 3.9 +  ARM64?

**Comment by wilsonzlin** [comment]
Yes it should for macOS and Linux (but not Windows), as mentioned in the README.md Python section.
