### ISSUE TITLE
TypeScript handling

### ISSUE THREAD

**Issue by nikeee** [wilsonzlin/minify-html#46]
I'm currently using this command to build + minify a TypeScript project with esbuild:
```sh
esbuild ./index.ts --bundle --minify --outfile=index.js
```

How, I also have CSS as well as HTML. The index.js is basically just referenced in the index.html.

Is it possbible to use minify-html and still keep the TypeScript support that esbuild offers?

If so, how? Does something like this work and will the reference changed to `.js`?
```html
<script src="index.ts">
```

**Comment by wilsonzlin** [comment]
Closing this for now. Feel free to reopen if there are further questions.

**Comment by nikeee** [comment]
In case someone has a similar problem: I'm currently testing Vite, which seems to do the thing above: https://vitejs.dev
