### ISSUE TITLE
Feature request: option for uppercase DOCTYPE

### ISSUE THREAD

**Issue by allan2** [wilsonzlin/minify-html#49]
Hi,

Could we get this as an option in `Cfg`?

Something like this:
```rust
cfg.do_not_minify_doctype = true;
cfg.uppercase_doctype = true;  // proposed
```

To get this:
```html
<!DOCTYPE html>minified
```

**Comment by wilsonzlin** [comment]
I had a look into why html-minifier uses a lowercase DOCTYPE and apparently it's [for better compression](https://github.com/kangax/html-minifier/issues/822), so I think I'll keep the current lowercase format. minify-html is not a formatter and the output is not optimised for human readability, so I'm reluctant to add flags and code for formatting preferences.
