### ISSUE TITLE
Support for Python 3.10

### ISSUE THREAD

**Issue by rehanhaider** [wilsonzlin/minify-html#50]
Right now trying to pip install minity-html results in 
```
ERROR: Could not find a version that satisfies the requirement minify-html (from versions: none)
ERROR: No matching distribution found for minify-html
```

Is support for Python 3.10 on the horizon?

**Comment by wilsonzlin** [comment]
I've added support for Python 3.10 in version `0.7.0`, let me know if it works for you.

**Comment by rehanhaider** [comment]
Thank you. I will test tomorrow and let you know. 

Much appreciated.
