### ISSUE TITLE
Template Literals

### ISSUE THREAD

**Issue by ecmel** [wilsonzlin/minify-html#52]
I am using https://pebbletemplates.io/  Pebble template engine and having problems using template literals in attribute values. Is it possible to leave template literals as is?

**Comment by wilsonzlin** [comment]
Currently minify-html doesn't handle any sort of templating syntax for the following reasons:
- There are lots of them (PHP, EJS, Mustache, JSP, Django, etc.), and it would involve integrating entire languages with all their syntaxes and edge cases, just to parse and skip over.
- It would incur a performance penalty, going against the goals of this project.
- It's outside minify-html's goal of doing one thing only and doing it well: minifying HTML.

**Comment by ecmel** [comment]
Pebble uses `{#  #}` `{% %}` and `{{  }}` as opening and closing literals may be just add the infrastructure in Configuration.Builder to add arbitrary characters as ignored.

**Comment by wilsonzlin** [comment]
I might take a look into adding ways to skip blocks of code purely based on matching pairs of sequences, since that minify-html already does that for preprocessor instructions. In your case, would there be any conflicting syntax in between opening and closing literals (e.g. `{# {# #}` or `{% {{ %} }}`)?

What are you using for chunked responses? I did originally intend to use direct byte buffers for better performance, but wasn't sure how usable it would be, so I'm interested in how Java users use the library and optimise performance.

You can turn off individual minification settings to debug specific minification features. Not sure how useful it'd be to have an option to disable any processing; wouldn't it be better to just not call the minifier? Without any processing only the internal parser would be tested and the library would effectively function as a passthrough.

**Comment by ecmel** [comment]
I am using micronaut framework for chunked responses.

{# #} this is for comments.
{{  }} this is for outputting variables.
{% %} this are directives.

They always start and end with those literals.

We can disable and enable minifiying CSS and JS so one can choose to minify only JS but not HTML

**Comment by che** [comment]
@ecmel  +1

We have also situation with broken HTML content.

Before minifiying:
`<meta charset="UTF-8">`
`<meta property="og:image:type" content="image/png">`
`<meta http-equiv="X-UA-Compatible" content="ie=edge">`
`<input placeholder=" " class="floating-input" id="id_username" maxlength="40" minlength="4" name="username" pattern="^[a-z][a-z0-9_\-\.].{1,39}[a-z0-9]$" required>`

After minifiying:
`<meta charset=UTF-8>`
`<meta property=og:image:type content=image/png>`
`<meta http-equiv=X-UA-Compatible content=ie=edge>`
`<input placeholder=" " class=floating-input id=id_username maxlength=40 minlength=4 name=username pattern=^[a-z][a-z0-9_\-\.].{1,39}[a-z0-9]$ required>`

How we can save quotes for HTML data values?
Thanks!

**Comment by Mupli** [comment]
@wilsonzlin  - I have same problem.  But different template engine. 
We need new arg "keep_quotes" or something. 
 
It should be doable fix - just to do not remove "" or '' in attributes, or disable attr parsing.

**Comment by leeola** [comment]
Configurable start and end tags would be useful, agreed. I run into this issue with [Sailfish](https://rust-sailfish.github.io/sailfish/syntax/overview/) *(Rust)*, which uses `<% %>`, `<%= %>`, `<%- %>` `<%+ %>`, and `<%# %>`. Of importance with Sailfish is that the start and end, differ.

**Comment by wilsonzlin** [comment]
I've just implemented support for parsing and preserving `<%`-style and brace-style (`{%`, `{{`, `{#`) templating syntax in HTML content. This is available in `0.14.0` and must be turned on via the `preserve_*` option(s).

If anyone manages to try this out, let me know how it goes.

I will implement support for attribute values next.

**Comment by Mupli** [comment]
@wilsonzlin  - share the link to follow the attr changes.

**Comment by wilsonzlin** [comment]
I've created an issue to support attributes at https://github.com/wilsonzlin/minify-html/issues/171.

**Comment by ginjo** [comment]
Not sure if this is same issue, or should be new.

I'm using Vue.js with template blocks like this `<script id="12345" type="text/x-template">`. They are reusable html blocks that are processed by Vue (this is one way to use Vue without a build step). However the html within these tags is not being minified. Is there a setting or trick to enable this, or is it not possible yet?

Here's an example block:

```html
<script id="tabs" type="text/x-template">
  <div class='tabs'>
    <ul>
      <li v-for='(tab, index) in tabs'
        :key='tab.title'
        @click='selectTab(index)'
        :class='{"is-active": (index == selectedIndex)}'
      >
        <a>{{ tab.title }}</a>
      </li>
    </ul>
  </div>
  <slot></slot>
</script>
```
