### ISSUE TITLE
Install fails on Debian

### ISSUE THREAD

**Issue by jalsco** [wilsonzlin/minify-html#53]
For me it fails on first step: `pip install minify-html`

`ERROR: Could not find a version that satisfies the requirement minify-html (from versions: none)`
`ERROR: No matching distribution found for minify-html`

I am running Debian 10 (buster) and python 3.7.3

**Comment by jalsco** [comment]
It is running on `ARM` processor. I also tried 

`pip install minify-html==0.6.10`  

and either   `_` `-` in the name

**Comment by wilsonzlin** [comment]
Only Python versions 3.8 to 3.10 are currently supported. This is mentioned in the README in the Python section.

**Comment by jalsco** [comment]
Thank you for explaining ! 👍🏻 I will waiting until latest Debian (atow: v10 buster) supports higher than 3.7. Currently 3.7 is the latest available for my environment

**Comment by wilsonzlin** [comment]
No problem. You can also use `0.6.10` if you'd like; there's no functional change from that to the current version (`0.7.0`), but it supports Python 3.7. The latest version mostly dealt with ARM64 support.

Alternatively, the Python library can be built from source without much difficulty (Node.js, Golang, Rust, and Python need to be installed):

```bash
bash ./prebuild.sh
cd python
python prepare.py js
cargo build --release
```

The built Python native module will be in `python/target/release`. Move it somewhere, and then simply import it from Python.
