### ISSUE TITLE
Minify-html breaks some pages, but most work - feedback 

### ISSUE THREAD

**Issue by jalsco** [wilsonzlin/minify-html#54]
Hi there, and Thank-you for some really nice software ! 

I upgraded to Debian 11 (Python 3.9) and the installation was easy.  Am developing a blog website using Pelican SSG, I noticed some pages break after using Minify-html.   Many pages do not break.  **As my site is not released yet I cannot put a link here.**   

Is some way to send in feedback about pages that Minify-html does not currently handle.  So future versions can handle a wider variety. 

Suggestion:  I would like to include a `tag` in my pages to say to minify-html "do not minify this page". The reason is that I call minify-html (automated) to minify all my html pages. Most work, but some do not. So I would do these steps 1. run minify-html across all pages.  2. manually check which pages look bad 3. add the `minify-html-skip` tag to the bad pages 4. rerun  minify-html (automated) across all pages ...

**Comment by wilsonzlin** [comment]
Feel free to provide any sample HTML here via GitHub issues and I can take a look. Only small reproducible example samples need to be provided, not the original source. Also, have you tried using the options that disable various minification features? Some minifications make the output not spec compliant, and these can be turned off.

Regarding excluding specific files: that sounds like something outside the scope of this library and doesn't sound like something minify-html should handle, especially if you're calling the Python library directly. Shouldn't something like an `if file not in blacklist: minify_html(src)` work? With some more context on how the library is used I might be able to understand better.

**Comment by jalsco** [comment]
Thanks for reply. I have emailed those link to you `code@wilsonl.in`. Hope that's ok.

I agree your comments about the calling.   I will have another look at that code. Thanks again 😊🙏🏻

**Comment by wilsonzlin** [comment]
I don't seem to be able to fetch the provided webpages, due to some connection error (possibly on my end). Nonetheless, it'd probably be better to provide isolated reproducible HTML snippets here instead, so that others can also take a look, there's a log of the issues and resolutions, and others do not have to manually crawl an unknown webpage. Feel free to open new issues if there are still problems, and provide the offending HTML in the issue.
