### ISSUE TITLE
Whitespace left in svg tags

### ISSUE THREAD

**Issue by elimintz** [wilsonzlin/minify-html#56]
Hi,

In SVG tags the whitespace between tags is not removed.

Below is a simplified example.

When using the python interface to minify:
```html
<svg> <path> </path> <path> </path> </svg>
```
Results in the same string as output:
```html
<svg> <path> </path> <path> </path> </svg>
```

Is there a way to configure the program to remove the whitespace between the tags?

Thank you for your time.

**Comment by wilsonzlin** [comment]
Thanks for raising, I've added whitespace minification rules for SVG elements in version `0.8.0`. Let me know if it works.

**Comment by elimintz** [comment]
Upgraded to 0.8.0 and it works great. Thank you!
