### ISSUE TITLE
onepass libraries missing?

### ISSUE THREAD

**Issue by adamchainz** [wilsonzlin/minify-html#60]
Thank you for a wonderful project. I'm building a Django integration for it.

The README currently points to the onepass libraries as a faster option, but they don't exist as advertised in the onepass library, e.g. https://pypi.org/project/minify-html-onepass/ is a 404.

Are they still pending release?

Thanks!

**Comment by baseplate-admin** [comment]
Yep, the library is not included by PyO3 when compiling.

**Comment by wilsonzlin** [comment]
I've implemented the onepass variant for Python as of version `0.9.2`. Let me know how it goes if you try it out.

**Comment by adamchainz** [comment]
Thanks, I have made an issue to add support to my Django package: https://github.com/adamchainz/django-minify-html/issues/51
