### ISSUE TITLE
The semicolon is not used at the end of the special character in the code

### ISSUE THREAD

**Issue by DamianHayden** [wilsonzlin/minify-html#64]
Display on the surface 
`<code><h2> <h3> <h4></code>`

View in source code
`<code>&LTh2> &LTh3> &LTh4></code>`

The browser is assisted and looks correct, but the warning is displayed on the source, so I was a little worried about it.

**Comment by wilsonzlin** [comment]
Yes, for specific entities where semicolon is optional and it is safe to do so, minify-html will remove the trailing semicolon. Currently there is no way to turn this off as it should be harmless in all browsers (it's allowed by the spec) and saves extra bytes. What's the warning shown in the browser?

**Comment by DamianHayden** [comment]
`Character reference was not terminated by a semicolon`
A sentence like this is displayed.
However, when I looked it up, it seems that this can only be seen by browsing the source code in firefox or in the console of ie. Nothing was pointed out in chrome.
As you say, it's safe, and now it may not be a concern.

**Comment by wilsonzlin** [comment]
OK, sounds like there's no issue here, so will close.
