### ISSUE TITLE
Attribute `type` removed for <button> element

### ISSUE THREAD

**Issue by che** [wilsonzlin/minify-html#69]
For `<button>` https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

Before minifiying:
`<button type="submit" class="submit-btn-form" disabled>`

After minifiying:
`<button class=submit-btn-form disabled>`

Why attribute `type` has been removed?

Config `minify_args` for Python:

```
    minify_args = {
        "do_not_minify_doctype": True,
        "ensure_spec_compliant_unquoted_attribute_values": True,
        "keep_closing_tags": True,
        "keep_comments": False,
        "keep_html_and_head_opening_tags": True,
        "keep_spaces_between_attributes": True,
        "minify_css": False,
        "minify_js": False,
        "remove_bangs": False,
        "remove_processing_instructions": False,
    }
```

**Comment by figgyc** [comment]
It's removed because the minifier [sees in the html-data](https://github.com/wilsonzlin/html-data/blob/master/data/data.json#L466) that `submit` is the default value for type on buttons. (That is also mentioned in the MDN post.) Therefore its removal should not change the functionality of the page.

**Comment by wilsonzlin** [comment]
@figgyc is correct, it's removed because it's the default value for the attribute. Are you encountering issues due to its removal?

**Comment by wilsonzlin** [comment]
Closing for now, feel free to reopen if issues arise.
