### ISSUE TITLE
Character `&#x2F;` becomes `%` instead of `/`

### ISSUE THREAD

**Issue by augustinreille** [wilsonzlin/minify-html#7]
I use Zola as a static website generator.

It provides as an output links like this : 
`<link href="http:&#x2F;&#x2F;areille.com&#x2F;style.css" rel="stylesheet">`

which becomes after minification (with CLI) : 
`<link href=http:%%areille.com%style.css rel=stylesheet>`

https://www.codetable.net/hex/2f

**Comment by wilsonzlin** [comment]
Thanks for raising this issue, I've fixed it in the latest release `0.3.6`. I've tested on the input again, it appears to be working correctly now. Let me know if it's fixed for you.

**Comment by augustinreille** [comment]
LGTM. Thanks a lot !
