### ISSUE TITLE
Optional fix for invalid HTML

### ISSUE THREAD

**Issue by jen6** [wilsonzlin/minify-html#70]
I used version 0.4.10 and also saw issue #34. It had a breaking change on 0.5.0 which make the fix invalid HTML.
Is it possible to make an optional flag to fix invalid HTML? It was easy to recognize when I made mistakes.
Also, the user's input can change HTML or js in general use cases. When it makes invalid HTML I hope to return the original HTML to know mistakes easily not automated fix.

**Comment by wilsonzlin** [comment]
If I understand correctly, you want to have the option for a more strict parser, like in previous versions, where it was possible for an error to be returned? If so, I don't think this will be possible, as I'm moving towards a best-effort parsing model like browsers. However, ensuring the validity of HTML input is not minify-html's responsibility, and there are plenty of HTML validators out there available.

**Comment by bobort** [comment]
I came over here from https://github.com/kangax/html-minifier looking for basically a Python version of it. The author of that library is opinionated about valid HTML, and I think he's right. We should only be outputting valid HTML. His library makes the strict assumption that the HTML input is already valid, and I see no reason why this library couldn't do the same thing. We should only be working with valid HTML.

Browsers made a mistake by accepting malformed HTML; they became bloated and slow to consider all the potential enumerations of an invalid HTML document. It is on HTML developers to make valid HTML only.
