### ISSUE TITLE
os.arch aarch64 not supported (Java version)

### ISSUE THREAD

**Issue by potpot59** [wilsonzlin/minify-html#73]
Error:

`Platform not supported (os.name=mac os x, os.arch=aarch64)`

Version:

`0.8.0`

**Comment by wilsonzlin** [comment]
Currently minify-html does not support Java on ARM-based macOS. The build infra is there, so I'll see if I can get it included in the build pipeline; not sure if there'll be any issues with JNI, ARM, and macOS.

**Comment by potpot59** [comment]
> Currently minify-html does not support Java on ARM-based macOS. The build infra is there, so I'll see if I can get it included in the build pipeline; not sure if there'll be any issues with JNI, ARM, and macOS.

Thx you 😊

**Comment by wilsonzlin** [comment]
Unfortunately I'm no longer able to look into this, as I no longer have access to ARM-based macOS hardware. Once GitHub Actions provides ARM-based Macs I can look into this again. Alternatively it's possible to compile from source if desired.

**Comment by potpot59** [comment]
https://github.com/actions/runner-images/issues/2187
