### ISSUE TITLE
[Bug] Using pnpm to install throw a self signed error

### ISSUE THREAD

**Issue by wjq990112** [wilsonzlin/minify-html#75]
<img width="577" alt="image" src="https://user-images.githubusercontent.com/45777252/158734526-20ac43b0-43b7-4e0d-9e89-64e9ded9b53d.png">

Also throw the same error when install `@minify-html/js-esbuild`.

**Comment by wilsonzlin** [comment]
This is interesting, I've never encountered this issue before. The package does try to download binaries from `https://wilsonl.in`, which is powered by Cloudflare. Are you able to visit that website normally without TLS errors?

**Comment by wjq990112** [comment]
> This is interesting, I've never encountered this issue before. The package does try to download binaries from `https://wilsonl.in`, which is powered by Cloudflare. Are you able to visit that website normally without TLS errors?

```json
{
"code": "not_found",
"message": "File with such name does not exist.",
"status": 404
}
```

**Comment by wilsonzlin** [comment]
Looks like connecting to the website works. Is the error still occurring? I'm not as familiar with `pnpm`, and if it intercepts network requests from postinstall scripts or otherwise interferes with the install process. Might be worth raising with them.

**Comment by wilsonzlin** [comment]
Closing this for now, feel free to reopen if issues persist.
