### ISSUE TITLE
Can't install this 0.8.0 on Centos 7.9 w/ Python 3.9

### ISSUE THREAD

**Issue by SpyderZ** [wilsonzlin/minify-html#78]
When trying to install on Centos 7.9 I'm getting the following error:

```
ERROR: Could not find a version that satisfies the requirement minify-html==0.8.0 (from versions: none)
ERROR: No matching distribution found for minify-html==0.8.0
```

Compatible tags: 369
  cp39-cp39-manylinux_2_17_x86_64
  cp39-cp39-manylinux2014_x86_64
  cp39-cp39-manylinux_2_16_x86_64
  cp39-cp39-manylinux_2_15_x86_64
  cp39-cp39-manylinux_2_14_x86_64
  cp39-cp39-manylinux_2_13_x86_64
  cp39-cp39-manylinux_2_12_x86_64
  cp39-cp39-manylinux2010_x86_64
  cp39-cp39-manylinux_2_11_x86_64
  cp39-cp39-manylinux_2_10_x86_64
  cp39-cp39-manylinux_2_9_x86_64
  cp39-cp39-manylinux_2_8_x86_64
  cp39-cp39-manylinux_2_7_x86_64
  cp39-cp39-manylinux_2_6_x86_64
  cp39-cp39-manylinux_2_5_x86_64
  cp39-cp39-manylinux1_x86_64
  cp39-cp39-linux_x86_64

What's causing this? I have another server running Rocky Linux 8.5 and don't have this problem.

**Comment by wilsonzlin** [comment]
I'm not completely sure, but from `Compatible tags: 369` it seems like you're using Python 3.6? If so, that's not a supported version; the minimum version supported is 3.8 as mentioned in the README under the Python section.

Feel free to reopen if this is not the issue.
