### ISSUE TITLE
Missing double quotes for attributes and no spaces between attributes.

### ISSUE THREAD

**Issue by mgaller** [wilsonzlin/minify-html#8]
If use the following template (boostrap 3 base) i get two different errors:
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <h1>Hello, world!</h1>

<img class="lazyload img-responsive visible-xs" data-sizes="auto" data-srcset="
    
        /media/image150x150_q85.jpg 150w,
    
        /media/image320x320_q85.jpg 320w,
    
        /media/image600x600_q85.jpg 600w,
    
        /media/image900x900_q85.jpg 900w,
    
        /media/image1280x1280_q85.jpg 1280w,
    
        /media/image1500x1500_q85.jpg 1500w
    
    ">

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
  </body>
</html>     
```
### Missing double-quotes:
<meta http-equiv=X-UA-Compatible content=IE=edge>

### No space between attributes
<img class="lazyload img-responsive visible-xs"data-sizes=auto data-srcset="

Iam using:
Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit (AMD64)] on win32
minify_html-0.3.7-cp38-none-win_amd64.whl from pip

**Comment by wilsonzlin** [comment]
I'm not seeing any errors from the minifier on my end when I test with your provided sample input, either from the CLI or Python library, for version 0.3.7. minify-html should support unquoted attribute values; are these errors from the minifier or some application/library that's using the minified output HTML?

**Comment by mgaller** [comment]
Sry, by errors i mean errors that the w3c validator shows me

**Comment by wilsonzlin** [comment]
The minifier will produce HTML that doesn't validate, but will work in browsers. For example, removing spaces between attributes isn't technically valid but the browser will nonetheless interpret them as separate attributes. These are done to optimise the most bytes away without altering the behaviour when rendered by browser.

I will start to add more configuration options soon for features that save bytes but cause not well formed HTML code, so if conforming markup is needed they can be turned off.

**Comment by mgaller** [comment]
That makes sense, i was just a little bit scared because it still has to run in internet explorer 11
