### ISSUE TITLE
Build node Package while installing

### ISSUE THREAD

**Issue by aaka5h** [wilsonzlin/minify-html#82]
Hi There,

We would like to use the node.js package of this library. During install it seems to download binaries which in our organisation proxies block.
Can we have an option to build the node package during install if binary download fails.

Also the onepass packages are not available yet?

**Comment by wilsonzlin** [comment]
As of version `0.9.0` the Node.js library now uses Neon, which provides building from source support out of the box, so this should work now. Note that the Rust compiler must be installed. Also note that the version is a minor version change so there are small but breaking changes for the Node.js package, described in the changelog.

Currently I'm working on getting the bindings for minify-html-onepass out 😃
