### ISSUE TITLE
[FR] Improve the behavior while dealing with unmatched closing tags

### ISSUE THREAD

**Issue by Rongronggg9** [wilsonzlin/minify-html#86]
https://github.com/wilsonzlin/minify-html/blob/master/notes/Parsing.md says `If a closing tag does not match the opening tag, and the closing tag cannot be omitted as per the spec, the closing tag is reinterpreted as an opening tag. NOTE: Most browsers have far more complex logic`. It is quite rude behavior and self-degradation, only making anything worse than doing nothing.

# Consider such a case...

## Example
```html
A <a href=https://example.com>nice </p>example</a> is here!
```

## Firefox/Chromium renders it as...
```html
A <a href="https://example.com">nice <p></p>example</a> is here!
```
![](https://user-images.githubusercontent.com/15956627/172690847-44f08298-8d6e-4991-a7d9-9a8a5132f4fc.png)

## `minify-html` mimifies it as...
```html
A <a href=https://example.com>nice <p>example<a> is here!
```

## Firefox/Chromium renders the minified HTML as...
```html
A <a href="https://example.com">nice </a><p><a href="https://example.com">example</a><a> is here!</a></p>
```
### Firefox
![](https://user-images.githubusercontent.com/15956627/172691040-8c13e186-0f28-41c2-a515-7dabdeb7a178.png)

### Chromium
![](https://user-images.githubusercontent.com/15956627/172691181-1fe4933d-b4aa-41c9-92bc-cbc975289ad4.png)
`is here!` uncolored, but the rendered document tree is the same.

# This is a real case!

What if the example is like...
```html
A <a href=https://example.com>nice </p>example</a> is here!
A <a href=https://example.com>nice </p>example</a> is here!
A <a href=https://example.com>nice </p>example</a> is here!
A <a href=https://example.com>nice </p>example</a> is here!
A <a href=https://example.com>nice </p>example</a> is here!
A <a href=https://example.com>nice </p>example</a> is here!
...
...
```

**Terrible nesting will occur after minified by `minify-html`!**

**This is a real case ([real_case.tar.gz](https://github.com/wilsonzlin/minify-html/files/8864318/real_case.tar.gz)).** If an HTML is generated **using a malformed template**, such an isolated closing tag could appear **a great many times**!

## Firefox/Chromium renders the end of the source HTML as...
![](https://user-images.githubusercontent.com/15956627/172698650-fd04d75c-5938-4a35-9f8a-ee5fed930a36.png)

![](https://user-images.githubusercontent.com/15956627/172698805-ebaa52e1-b4ab-4e97-8dc9-82e3d7cd0c85.png)

## Firefox renders the end of the minified HTML as...
![](https://user-images.githubusercontent.com/15956627/172699315-ccdad75b-25a2-411e-9212-99d76bcb1528.png)

![](https://user-images.githubusercontent.com/15956627/172699258-f32af802-fd1e-4616-a2ae-1f643af3bfb8.png)

Loading the page took some time. The DevTool was extremely lagging.

## Chromium renders the minified HTML as...
![](https://user-images.githubusercontent.com/15956627/172697718-3ffd860d-20f3-43cc-813f-2761616b82b0.png)

Crashed.

# Suggested solution

Since `minify-html` is a document-tree-free HTML minifier, copying the behavior of browsers is difficult. There is still a better solution to simulate the behavior of browsers mostly:
1. Unmatched opening orphan tag, leave it as is (current behavior).
2. Unmatched opening child tag, close it just before its parent is closed.
3. Unmatched closing tag, child or orphan, except the case of rule 2, add an opening tag just before it.

| rule | source | minified (current) | minified (suggested) |
| ---- | ------ | ------------------ | -------------------- |
| 1 | `1<orphan>2` | `1<orphan>2` | `1<orphan>2` |
| 2 | `1<parent>2<unmatched>3</parent>4` | `1<parent>2<unmatched>3<parent>4` | `1<parent>2<unmatched>3</unmatched></parent>4` |
| 3 | `1</unmatched>2` | `1<unmatched>2` | `1<unmatched></unmatched>2` |
| 3 | `1<parent>2</unmatched>3</parent>4` | `1<parent>2<unmatched>3<parent>4` | `1<parent>2<unmatched></unmatched>3</parent>4` |
| 2&3 | `1<div>2<span>3</div>4</span>5` | `1<div>2<span>3<div>4<span>5` | `1<div>2<span>3</span></div>4<span></span>5` |

In this way, the behavior simulates most browsers furthest and won't break their renderers in most cases.

**Comment by wilsonzlin** [comment]
Thanks for raising the issue. It does seem like the current approach opens up the possibility to cause an explosion in the document tree with particularly malformed inputs. I think I will update the approach for unrecognised closing tags to simply ignore them completely. I don't want to add any HTML as that will remove the guarantee that the output is never larger than the input, which is very important for performance as this allows for in-place minification, guaranteed memory allocation, etc. Any approach that requires knowing anything other than the parent element should be avoided too.

**Comment by Rongronggg9** [comment]
Thanks for your explanation. I agree that your decision that makes `minify-html` simply ignore them is quite reasonable. Any parser building document tree should deal with them properly (not resulting in a crash) in most cases.

**Comment by wilsonzlin** [comment]
I've changed the parsing behaviour now to simply drop the mismatched closing tags. This will be included in the next release cut.

**Comment by Rongronggg9** [comment]
Hmm... v0.10.0 does produce different output than v0.8.0, but I don't think the document tree explosion issue has been solved.

Firefox: The end of the minified HTML is still malformed and the document tree still explodes.
<details>

![](https://user-images.githubusercontent.com/15956627/188541467-1ec84b7f-8db7-4234-9442-ef9ab48d9fb4.png)
![](https://user-images.githubusercontent.com/15956627/188540832-8514ed8f-bc3b-4a21-adbc-9b86f2f33b39.png)
</details>

Chrome: Takes a long time to load the page and the inspector crashes.

[reproduce.tar.gz](https://github.com/wilsonzlin/minify-html/files/9493056/reproduce.tar.gz)
Cfg:
```
do_not_minify_doctype
ensure_spec_compliant_unquoted_attribute_values
keep_closing_tags
keep_spaces_between_attributes
```

If it confirmed to be unsolved, could you please re-open the issue?

**Comment by Rongronggg9** [comment]
Slightly looking back to the issue, I realized that "simply drop the mismatched closing tags" won't help solve the explosion in such a case.

<hr>

This is the minimal problematic chunk in the source HTML (prettified), it repeats tons of times:

```html
<div class='bg-square-2020'>
    <div class='link-2020'>
        <a href="https://example.com">
            <br/>
            <img class="img-2020" src="https://example.com">
            </p> <!-- mismatched -->
            <div class='tag-container-2020'>
                <div class='tag-v2-1-2020 tag-PS4-2020'>PS4</div>
                </p> <!-- mismatched -->
            </div>
            <div class='price-2020'>
                <div class='new-price-2020'>R$ 123,67</div>
                <div class='old-price-2020'>R$ 164,90</div>
                </p> <!-- mismatched -->
            </div>
            <div class='title-2020'>Skater XL</div>
            <p> <!-- unclosed -->
        </a> <!-- should it be mismatched? -->
    </div> <!-- should it be mismatched? -->
</div> <!-- should it be mismatched? -->
```

Minified (v0.10.0, prettified, cfg refer to the previous reply):

```html
<div class=bg-square-2020>
    <div class=link-2020>
        <a href=https://example.com>
            <br>
            <img class=img-2020 src=https://example.com>
            <div class=tag-container-2020>
                <div class="tag-v2-1-2020 tag-PS4-2020">PS4</div>
            </div>
            <div class=price-2020>
                <div class=new-price-2020>R$ 123,67</div>
                <div class=old-price-2020>R$ 164,90</div>
            </div>
            <div class=title-2020>Skater XL</div>
            <p>
```

The problem locates at the opening `<p>` inside other tags. `minify-html` considered it valid and did not close it, making `</a></div></div>` below mismatched and being dropped. Repeat once, nest 4 levels.

I am not sure how `minify-html` is implemented. Is there something like a stack storing tags waiting to be closed while processing? If so, is rule 2 (`1<parent>2<mismatched>3</parent>4` -> `1<parent>2<mismatched>3</mismatched></parent>4`) possible to be implemented?

<hr>

In conclusion, the parsing behavior change in v0.10.0 only eliminates document tree explosion when:
* there are accidentally inserted closing tags (`<parent></inserted></parent>`)
But these two scenarios are still vulnerable:
* there are accidentally inserted opening tags (`<parent><inserted></parent>`)
* there are accidentally swapped tags (`<parent><child></parent></child>`)

I consider there are 4 workarounds:

1. `1<parent>2<mismatched>3</parent>4` -> `1<parent>2<mismatched>3</mismatched></parent>4`
2. An option to simply ignore all mismatched closing tags (is it really possible?)
3. An option to fail when mismatched closing tags detected
4. Warn users of the vulnerable behavior dealing with opening tags inside other tags in the README and suggest they should verify input first (seriously?)

**Comment by wilsonzlin** [comment]
I don't think those options are tenable given `minify-html` doesn't use a stack for performance reasons (it's able to work on a constant stream of bytes with constant memory), and implementing these arbitrary handling would add complexity not for minification and unfairly penalise every execution (going against the goals of being the fastest). minify-html is a single-responsibility tool that operates on HTML (not invalid HTML i.e. anything else), so if there's possibility of invalid inputs, I'd suggest running them through a dedicated validator/syntax checker tool first and touch up the inputs before running them through minify-html. I may look into adding the option for strict checking and bailing out when there's a syntax error; the current errorless mode was adopted due to users complaining about the strictness and friction.
