### ISSUE TITLE
Installation failing in python alpine image

### ISSUE THREAD

**Issue by ramsrib** [wilsonzlin/minify-html#88]
Pip installation  is failing in python alpine docker image. 

**Error message**
```
#5 3.671 ERROR: Could not find a version that satisfies the requirement minify-html (from versions: none)
#5 3.672 ERROR: No matching distribution found for minify-html
```

**Example Dockerfile** 
```Dockerfile
FROM python:3.9.0-alpine

RUN pip3 install --upgrade pip && \
    pip3 install --no-cache-dir minify-html
``` 

Is there any fix or workaround for this issue?

**Comment by wilsonzlin** [comment]
I believe this is due to missing glibc, which is required by the library and the default target when compiling the Rust library. You can try installing that, or compiling from source targeting another libc like musl.
