### ISSUE TITLE
TypeError with several keyword arguments in Python

### ISSUE THREAD

**Issue by adbar** [wilsonzlin/minify-html#91]
Hi, thanks for the nice package!

Although I'm using the example from the Python documentation I get the following error:

```
>>> import minify_html
>>> minify_html.minify("<p>  Hello, world!  </p>", minify_js=True, remove_processing_instructions=True)
TypeError: minify() got an unexpected keyword argument: remove_processing_instructions
```

Everything works fine with a single keyword argument.

**Comment by wilsonzlin** [comment]
I'm unable to reproduce this issue on my machine. Which version of the Python library are you using? Try doing a clean install of the latest version and see if the issue still exists.

**Comment by adbar** [comment]
I confirm it has been solved in the meantime, it works now, thanks!
