### ISSUE TITLE
Bug: Closing tags are kept when opening tags are removed

### ISSUE THREAD

**Issue by polarathene** [wilsonzlin/minify-html#93]
### Input

```html
<!DOCTYPE html><html lang="en-US"><head></head><body><p>█</p><p>&#9608;</p></body></html>
```

### Output (`./minify-html-cli --keep-closing-tags index.html`)

```html
<!doctypehtml><html lang=en-US></head><body><p>█</p><p>█</p></body></html>
```

### Expected

```html
<!doctypehtml><html lang=en-US><body><p>█</p><p>█</p></body></html>
```

**Comment by wilsonzlin** [comment]
This isn't a bug, the spec defines different rules for omitting opening and closing tags, and omitting `<head>` does not automatically imply `</head>` can be omitted too. Refer to the [WHATWG spec](https://html.spec.whatwg.org/multipage/syntax.html#optional-tags) for more details.

I may look into adding the functionality to also omit closing `</head>` tags where possible in the future, however the rules for it are a bit more complex than other omission rules.

**Comment by polarathene** [comment]
Ok then, so `--keep-html-and-head-opening-tags` should be used if a lone `</head>` is undesirable?

I only noticed it due to syntax highlighting breaking. Not a problem then, thanks :+1:

**Comment by wilsonzlin** [comment]
Yes, using that option should keep the `<head>` opening tag.
