### ISSUE TITLE
Bug: Attributes are quote stripped with no option to opt-out

### ISSUE THREAD

**Issue by polarathene** [wilsonzlin/minify-html#94]
### Input

```html
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="1060" height="601.04"><rect width="1060" height="601.04" rx="5" ry="5" class="a"/></svg>
```

### Output 

With command:

```bash
./minify-html-cli \
  --keep-closing-tags \
  --do-not-minify-doctype \
  --ensure-spec-compliant-unquoted-attribute-values \
  --keep-html-and-head-opening-tags \
  --keep-spaces-between-attributes \
  test.svg
```

```html
<svg height=601.04 width=1060 xmlns=http://www.w3.org/2000/svg xmlns:xlink=http://www.w3.org/1999/xlink><rect class=a height=601.04 rx=5 ry=5 width=1060 /></svg>
```

### Expected

```html
<svg height="601.04" width="1060" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><rect class="a" height="601.04" rx="5" ry="5" width="1060"/></svg>
```

---

It doesn't seem to matter what options are used, the attribtues are stripped of quotes.

The original input that triggered this was a much larger SVG file containing CSS. As SVG can be embedded into HTML I assumed this tool would be able to minify SVG as well.

It remains an issue when in an HTML file:

```html
<!DOCTYPE html>
<html lang="en-US">
  <body>
    <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="1060" height="601.04">
      <rect width="1060" height="601.04" rx="5" ry="5" class="a"/>
    </svg>
  </body>
</html>
```

Which outputs to:

```html
<!doctype html><html lang=en-US><body><svg height=601.04 width=1060 xmlns=http://www.w3.org/2000/svg xmlns:xlink=http://www.w3.org/1999/xlink><rect class=a height=601.04 rx=5 ry=5 width=1060 /></svg></body></html>
```

The browser (Chromium) fails to render this with the following error:

```
error on line 1 at column 2: StartTag: invalid element name
```

Correcting `<!doctype html>` to `<!DOCTYPE html>` resolves that, then the next rendering error is:

```
error on line 1 at column 27: AttValue: " or ' expected
```

Requiring attributes to be quoted.

**Comment by wilsonzlin** [comment]
I can't reproduce the latter issue; when I open the HTML in Chrome, there are no errors and the SVG element renders correctly. I'm also unsure where those error messages came from, as browsers should never fail to render due to syntax errors. I could only reproduce the error if I rename the file to the `.svg` extension or declare a `image/svg+xml` Content-Type, which is incorrect as it's HTML, not SVG.

Currently there is no option to disable quote stripping from attributes. minify-html's primary goal is to provide super fast HTML minification for use in browsers, in competition with other tools in this arena. For SVG, I'd suggest using `svgo`, which has more tailored optimisations for SVG.

**Comment by polarathene** [comment]
> I could only reproduce the error if I rename the file to the `.svg` extension or declare a `image/svg+xml` Content-Type, which is incorrect as it's HTML, not SVG.

I can confirm that. Sorry I must have forgotten to change the `.svg` to `.html` for the HTML output.

> which is incorrect as it's HTML, not SVG.

Agreed.

---

So if I plan to embed the SVG into an HTML document, it's perfectly fine so long as `minify-html` is strictly used on the `.html` document itself.

I wrongly assumed that what was valid SVG when embedded into an HTML document, was valid as an SVG document :sweat_smile: 

> For SVG, I'd suggest using `svgo`, which has more tailored optimisations for SVG.

Yes, I've been using that to minify SVG prior to sometimes embedding into an HTML document :+1:
