### ISSUE TITLE
Remove of input[type='text'] breaks tailwind

### ISSUE THREAD

**Issue by krtko1** [wilsonzlin/minify-html#95]
https://github.com/tailwindlabs/tailwindcss-forms uses input[type='text'] to style input elements. But mimify-html removes it, so elements ends up unstylized.

**Comment by wilsonzlin** [comment]
`text` is the default value for the `type` attribute on `<input>` elements, so it's correct to omit it for minification purposes. This sounds more like a tailwind issue, as they should have CSS rules like `input:not([type]), input[type=text]`.

**Comment by synchronizing** [comment]
Is there a way to disable this minification via minify-html?
