### ISSUE TITLE
npm ERR! Failed to download @minify-html/js-esbuild: Error: Bad status of 404

### ISSUE THREAD

**Issue by volker-schukai** [wilsonzlin/minify-html#98]
The following call leads to an error:

```bash
 npm in @minify-html/js-esbuild
``` 

```
npm ERR! Failed to download @minify-html/js-esbuild: Error: Bad status of 404
``` 

In the [postinstall.js#L9](https://github.com/wilsonzlin/minify-html/blob/master/nodejs/postinstall.js#L9) file, a download URL is assembled from the architecture, operating system, and version.

```js
const binaryName = [process.platform, process.arch, process.versions.modules].join('__');
```

On my system this results in the following URL: `https://wilsonl.in/minify-html/bin/nodejs/0.2.6/linux__x64__92.node`

This leads in the following to a 404 during the installation via npm.

```js
{
code: "not_found",
message: "File with such name does not exist.",
status: 404
}
```

**Comment by wilsonzlin** [comment]
Version `0.2.6` is very old, and I'm not sure if it was built for the specified Node.js version. Where did you get the package name from? The docs mentions the package name is `@minify-js/node`, and the latest version is `0.10.0`. Try installing the latest package and let me know if it works.

**Comment by volker-schukai** [comment]
You have now successfully confused me completely. :smile:
You mean @minify-html/node and not @minify-js/node?

```bash
npm view @minify-html/node versions
[ '0.9.0', '0.9.1', '0.9.2' ]
```

but that works, I thought I tried that earlier.

```bash
npm init
npm install @minify-html/node
```

I don't know how I came up with the other one either. 


Sorry for wasting your time and thanks for the support.

**Comment by wilsonzlin** [comment]
Sorry, yes I meant `@minify-html/node`, got it mixed up with [my other project](https://github.com/wilsonzlin/minify-js), which has a similar name.
