### ISSUE TITLE
Minification of empty SVG differs from Browser Interpretation

### ISSUE THREAD

**Issue by winstonewert** [wilsonzlin/minify-html#99]
My html:

```
<a>
    <svg viewBox="0 0 700 100" />
</a>
<footer>
</footer>
```

This minimizes to:

`<a> <svg viewbox="0 0 700 100"><a> <footer></footer>`

I'm not sure of the validity of a self-closing svg tag. But, Chrome and Firefox interpret it as an empty svg element. However, after going through the minifier it interprets it as `footer` inside an `a` inside `svg` inside `a`.

I think this is probably the answer to the TODO here: https://github.com/wilsonzlin/minify-html/blob/c5bfac177c691fb887271154751efce773df3b67/rust/main/src/parse/element.rs#L157, the svg element is considered to be part of the svg namespace and thus should follow svg rules regarding self-closing tags.

**Comment by wilsonzlin** [comment]
Yes, I think the `<svg>` element should be treated within the `svg` namespace and allowed to be self-closing. Happy to receive any PRs on this.
